import { TimeEstimationParameter } from '../types';

export const DEFAULT_TIME_PARAMETERS: Omit<TimeEstimationParameter, 'id' | 'last_updated'>[] = [
    // Residential Defaults
    {
        building_type: 'Residential',
        height_category: 'Low-Rise (<15m)',
        excavation_timeline_months: 2,
        excavation_timeline_months_min: 1.5,
        excavation_timeline_months_max: 3,
        foundation_timeline_months: 2,
        foundation_timeline_months_min: 1.5,
        foundation_timeline_months_max: 3,
        structure_per_floor_days: 15,
        structure_per_floor_days_min: 10,
        structure_per_floor_days_max: 21,
        finishing_per_floor_days: 20,
        finishing_per_floor_days_min: 15,
        finishing_per_floor_days_max: 30,
        services_overlap_factor: 0.3,
        contingency_buffer_months: 2,
        delay_factors: {
            monsoon_pct: 30,
            summer_pct: 15,
            festival_pct: 12,
            winter_pct: 8,
            rework_pct: 15,
        },
    },
    {
        building_type: 'Residential',
        height_category: 'Mid-Rise (15-45m)',
        excavation_timeline_months: 3,
        excavation_timeline_months_min: 2,
        excavation_timeline_months_max: 5,
        foundation_timeline_months: 4,
        foundation_timeline_months_min: 3,
        foundation_timeline_months_max: 6,
        structure_per_floor_days: 12,
        structure_per_floor_days_min: 8,
        structure_per_floor_days_max: 16,
        finishing_per_floor_days: 18,
        finishing_per_floor_days_min: 12,
        finishing_per_floor_days_max: 25,
        services_overlap_factor: 0.5,
        contingency_buffer_months: 3,
        delay_factors: {
            monsoon_pct: 30,
            summer_pct: 15,
            festival_pct: 12,
            winter_pct: 10,
            rework_pct: 15,
        },
    },
    {
        building_type: 'Residential',
        height_category: 'High-Rise (>45m)',
        excavation_timeline_months: 5,
        excavation_timeline_months_min: 3,
        excavation_timeline_months_max: 8,
        foundation_timeline_months: 6,
        foundation_timeline_months_min: 4,
        foundation_timeline_months_max: 10,
        structure_per_floor_days: 8,
        structure_per_floor_days_min: 5,
        structure_per_floor_days_max: 12,
        finishing_per_floor_days: 15,
        finishing_per_floor_days_min: 10,
        finishing_per_floor_days_max: 20,
        services_overlap_factor: 0.7,
        contingency_buffer_months: 4,
        delay_factors: {
            monsoon_pct: 35,
            summer_pct: 15,
            festival_pct: 12,
            winter_pct: 10,
            rework_pct: 18,
        },
    },

    // Commercial Defaults
    {
        building_type: 'Commercial',
        height_category: 'Low-Rise (<15m)',
        excavation_timeline_months: 1.5,
        excavation_timeline_months_min: 1,
        excavation_timeline_months_max: 2.5,
        foundation_timeline_months: 2,
        foundation_timeline_months_min: 1.5,
        foundation_timeline_months_max: 3,
        structure_per_floor_days: 12,
        structure_per_floor_days_min: 8,
        structure_per_floor_days_max: 16,
        finishing_per_floor_days: 15,
        finishing_per_floor_days_min: 10,
        finishing_per_floor_days_max: 20,
        services_overlap_factor: 0.4,
        contingency_buffer_months: 2,
        delay_factors: {
            monsoon_pct: 25,
            summer_pct: 12,
            festival_pct: 10,
            winter_pct: 8,
            rework_pct: 12,
        },
    },
    {
        building_type: 'Commercial',
        height_category: 'Mid-Rise (15-45m)',
        excavation_timeline_months: 3,
        excavation_timeline_months_min: 2,
        excavation_timeline_months_max: 5,
        foundation_timeline_months: 4,
        foundation_timeline_months_min: 3,
        foundation_timeline_months_max: 6,
        structure_per_floor_days: 10,
        structure_per_floor_days_min: 7,
        structure_per_floor_days_max: 14,
        finishing_per_floor_days: 12,
        finishing_per_floor_days_min: 8,
        finishing_per_floor_days_max: 16,
        services_overlap_factor: 0.6,
        contingency_buffer_months: 3,
        delay_factors: {
            monsoon_pct: 28,
            summer_pct: 13,
            festival_pct: 10,
            winter_pct: 8,
            rework_pct: 14,
        },
    },
    {
        building_type: 'Commercial',
        height_category: 'High-Rise (>45m)',
        excavation_timeline_months: 5,
        excavation_timeline_months_min: 3,
        excavation_timeline_months_max: 8,
        foundation_timeline_months: 7,
        foundation_timeline_months_min: 5,
        foundation_timeline_months_max: 10,
        structure_per_floor_days: 7,
        structure_per_floor_days_min: 5,
        structure_per_floor_days_max: 10,
        finishing_per_floor_days: 10,
        finishing_per_floor_days_min: 7,
        finishing_per_floor_days_max: 14,
        services_overlap_factor: 0.8,
        contingency_buffer_months: 4,
        delay_factors: {
            monsoon_pct: 32,
            summer_pct: 15,
            festival_pct: 12,
            winter_pct: 10,
            rework_pct: 16,
        },
    }
];
